### ISSUE TITLE
最近两次commit导致当前head分支里有很多书被删掉了

### ISSUE THREAD

**Issue by gigberg** [anzhihe/learning#16]
git clone仓库后, 执行git checkout 15f6b08命令, 然后删掉.git隐藏文件夹即可

**Comment by anzhihe** [comment]
有个别书侵权了，有些书过大了，都干掉了

**Comment by yitian108** [comment]
@anzhihe 如何可以获取原来的书，例如awk and sed修订第三版.pdf

**Comment by anzhihe** [comment]
这本书仓库里有啊，clone下载就行了

**Comment by yitian108** [comment]
下载下来只有1KB
![sed-awk](https://github.com/anzhihe/learning/assets/3113836/8e9dfcd0-8728-4b7e-8dcd-126edf63f9d4)
此外，对于git clone 不成功，看起来一下载就被删除的样子
![image](https://github.com/anzhihe/learning/assets/3113836/f540cadb-715e-4f0f-942a-28cc264e7698)

**Comment by chenryn** [comment]
除了重构、leetcode、第一本算法书，其他所有下载下来都是 132 字节……能不能整个打包个网盘……

**Comment by anzhihe** [comment]
@chenryn @yitian108 @gigberg https://pan.baidu.com/s/11rzb9XuK2N4moX27KKuKcg?pwd=ik72，解压密码：chegva.com
