### ISSUE TITLE
重构 第二版 无法打开

### ISSUE THREAD

**Issue by NefelibataJay** [anzhihe/learning#19]
下载了重构 第二版 ，使用Edge打开显示，无法打开文件，出错了。

已经尝试使用其他应用仍然无法打开。

**Comment by anzhihe** [comment]
我本地应用，chrome浏览器都能打开

**Comment by T34-active** [comment]
好像文件损坏了 作者你看一下是不是没有上传成功

**Comment by T34-active** [comment]
> 好像文件损坏了 作者你看一下是不是没有上传成功

我把项目克隆下来了 很多文件都是1KB
