### ISSUE TITLE
PDF文件损坏

### ISSUE THREAD

**Issue by redfoxfox** [anzhihe/learning#20]
PDF文件几乎都看不了

**Comment by anzhihe** [comment]
你是在线看的？还是下载后本地看的？

**Comment by shwnyao** [comment]
鳳凰項目下載後顯示損壞

**Comment by anzhihe** [comment]
@shwnyao https://pan.baidu.com/s/11rzb9XuK2N4moX27KKuKcg?pwd=ik72，解压密码：chegva.com

**Comment by anzhihe** [comment]
@redfoxfox https://pan.baidu.com/s/11rzb9XuK2N4moX27KKuKcg?pwd=ik72，解压密码：chegva.com
